# Generated by Django 4.1.1 on 2022-09-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="patient_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pregnancies", models.CharField(max_length=50)),
                ("GLucose", models.CharField(max_length=50)),
                ("Blood_Pressure", models.CharField(max_length=50)),
                ("Skin_Thickness", models.CharField(max_length=50)),
                ("Insulin", models.CharField(max_length=50)),
                ("BMI", models.CharField(max_length=50)),
                ("DPF", models.CharField(max_length=50)),
                ("Age", models.CharField(max_length=50)),
                ("Result", models.CharField(max_length=50)),
            ],
        ),
    ]
