# Generated by Django 4.1.1 on 2022-09-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient_data",
            name="Username",
            field=models.CharField(default="", max_length=50),
        ),
    ]
